version: '3.7'

services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cars
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    ports: ['9000:9001']
    depends_on:
      - mysql
    volumes:
      - ./symfony/:/var/www/symfony:cached

  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony/:/var/www/symfony:cached

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql

  rabbitmq:
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 15630:15672
    env_file:
      - ./symfony/.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports: ['5601:5601']
    depends_on: ['elasticsearch']