logging.level: info
logging.to.files: false

#--------------------------------- log input ----------------------------------
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/logs/*.log'
    json.keys_under_root: true

    processors:
      - decode_json_fields:
          fields: ['message']
          target: json

#---------------------------- elasticsearch output ----------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: elastic
  password: changeme