# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    rabbitmq_host: '%env(string:LOCAL_IP)%'
    rabbitmq_user: 'cars'
    rabbitmq_password: 'cars'
    rabbitmq_statuslayer_vhost: '/'
    rabbitmq_port: 5630

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $uploadsPath: '%kernel.project_dir%/public/uploads'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Service\UploaderHelper:
        arguments:
            - '%env(PHOTOS_PATH)%'

    App\Infrastructure\Repository\CarElasticRepository:
        arguments:
            - '%env(LOCAL_IP)%'
            - '%env(PORT_ELASTIC)%'

    App\Infrastructure\Elasticsearch\LoggerElastic:
        arguments:
            - '%env(string:LOCAL_IP)%'

    App\Application\Command\Handler\:
        resource: '../src/Application/Command/Handler'
        tags: ['messenger.message_handler']

    App\Application\Query\Handler\:
        resource: '../src/Application/Query/Handler'
        tags: ['messenger.message_handler']

    log_service:
        class: App\Infrastructure\Rabbit\RabbitConsumer

    App\Infrastructure\Event\SymfonyDomainEventPublisher:
        arguments: ['@old_sound_rabbit_mq.logging_producer']

    App\Application\UseCases\Car\InsertCar:
        arguments:
            - '@App\Infrastructure\Repository\CarRepository'
            - '@App\Infrastructure\Repository\CarElasticRepository'
            - '@App\Infrastructure\Service\UploaderHelper'
            - '@App\Infrastructure\Event\SymfonyDomainEventPublisher'

    App\Application\UseCases\Car\DeleteCar:
        arguments:
            - '@App\Infrastructure\Repository\CarRepository'
            - '@App\Infrastructure\Repository\CarElasticRepository'
            - '@App\Infrastructure\Service\UploaderHelper'
            - '@App\Infrastructure\Event\SymfonyDomainEventPublisher'

    App\Application\UseCases\Car\UpdateCar:
        arguments:
            - '@App\Infrastructure\Repository\CarRepository'
            - '@App\Infrastructure\Repository\CarElasticRepository'
            - '@App\Infrastructure\Service\UploaderHelper'
            - '@App\Infrastructure\Event\SymfonyDomainEventPublisher'

    App\Application\UseCases\Car\GetCarInfo:
        arguments:
            - '%env(REPO_DATA)%'
            - '@App\Infrastructure\Factory\CarRepoFactory'

    App\Application\UseCases\Car\ListAllCars:
        arguments:
            - '%env(REPO_DATA)%'
            - '@App\Infrastructure\Factory\CarRepoFactory'

    App\Application\UseCases\Car\ListAllCarsEnabled:
        arguments:
            - '%env(REPO_DATA)%'
            - '@App\Infrastructure\Factory\CarRepoFactory'

    App\Application\UseCases\Car\ListCarsFiltered:
        arguments:
            - '%env(REPO_DATA)%'
            - '@App\Infrastructure\Factory\CarRepoFactory'

    App\Infrastructure\Factory\CarRepoFactory:
        arguments:
            - '@App\Infrastructure\Repository\CarRepository'
            - '@App\Infrastructure\Repository\CarElasticRepository'

imports:
    - { resource: packages/old_sound_rabbit_mq.yaml }